# Generated by Django 4.0.3 on 2022-04-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='DA',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='SERP',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='backlink',
        ),
    ]
