# Generated by Django 4.0.3 on 2022-04-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_remove_competitor_da_remove_competitor_serp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='Keyword',
            field=models.TextField(blank=True),
        ),
    ]
