# Generated by Django 4.0.3 on 2022-04-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0003_competitor_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='Keyword',
        ),
    ]
