# Generated by Django 4.0.3 on 2022-04-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0005_competitor_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitorkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.TextField(blank=True)),
                ('Search', models.IntegerField(blank=True)),
                ('Difficulty', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='Keyword',
        ),
    ]
