# Generated by Django 4.0.3 on 2022-04-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0006_competitorkey_remove_competitor_keyword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competitorkey',
            new_name='key',
        ),
    ]
