# Generated by Django 4.0.3 on 2022-04-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0007_rename_competitorkey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='Competename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
