# Generated by Django 4.0.3 on 2022-04-24 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0010_compare_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compare',
            old_name='name',
            new_name='names',
        ),
    ]
