# Generated by Django 4.0.3 on 2022-04-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0012_rename_names_compare_compare_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='Link',
            field=models.CharField(max_length=100),
        ),
    ]
