# Generated by Django 4.0.3 on 2022-04-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0013_alter_compare_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='Compare_name',
            field=models.CharField(max_length=100),
        ),
    ]
