# Generated by Django 4.0.3 on 2022-04-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0014_alter_compare_compare_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='key',
        ),
    ]
