# Generated by Django 4.0.3 on 2022-04-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0015_delete_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Competename', models.CharField(max_length=100, null=True)),
                ('Keyword', models.TextField(blank=True)),
                ('Search', models.IntegerField(blank=True)),
                ('Difficulty', models.IntegerField(blank=True)),
            ],
        ),
    ]
