# Generated by Django 4.0.3 on 2022-04-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0016_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compare',
            old_name='Compare_name',
            new_name='Link_a',
        ),
        migrations.RenameField(
            model_name='compare',
            old_name='Link',
            new_name='Link_b',
        ),
        migrations.RenameField(
            model_name='compare',
            old_name='Primary_Topic',
            new_name='Parameter',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Alexa_Rank',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Backlink_Educational',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Backlinks',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Domain_Authority',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Domain_Citation',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Domain_trust',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Educational_domains',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Governmental_refdomains',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Linking_IP_address',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Linking_domains',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Linking_subnets',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Nepal_Rank',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Organic_Search',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Page',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Primary_Topical_trust_flow',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Total_backlinks',
        ),
    ]
