# Generated by Django 4.0.3 on 2022-04-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0018_compare_comparename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='Link_a',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Link_b',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='Parameter',
        ),
    ]
