# Generated by Django 4.0.3 on 2022-04-24 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0019_remove_compare_link_a_remove_compare_link_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='Parameter',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
