# Generated by Django 4.0.3 on 2022-04-24 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0020_compare_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='Link_a',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
