# Generated by Django 4.0.3 on 2022-03-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competitor',
        ),
    ]
